package X;

import java.util.HashMap;
import org.wawebrtc.MediaCodecVideoEncoder;

/* renamed from: X.2Jo  reason: invalid class name and case insensitive filesystem */
public abstract class AbstractC47792Jo {
    public static final AnonymousClass0GF A00;
    public static final HashMap A01;
    public static final HashMap A02;

    static {
        AnonymousClass0GF r4 = new AnonymousClass0GF(255);
        A00 = r4;
        r4.A02("AC", new String[]{"SHP"});
        AnonymousClass0GF r15 = A00;
        r15.A02("AD", new String[]{"EUR"});
        r15.A02("AE", new String[]{"AED"});
        r15.A02("AF", new String[]{"AFN"});
        r15.A02("AG", new String[]{"XCD"});
        r15.A02("AI", new String[]{"XCD"});
        r15.A02("AL", new String[]{"ALL"});
        r15.A02("AM", new String[]{"AMD"});
        r15.A02("AO", new String[]{"AOA"});
        r15.A02("AR", new String[]{"ARS"});
        r15.A02("AS", new String[]{"USD"});
        r15.A02("AT", new String[]{"EUR"});
        r15.A02("AU", new String[]{"AUD"});
        r15.A02("AW", new String[]{"AWG"});
        r15.A02("AX", new String[]{"EUR"});
        r15.A02("AZ", new String[]{"AZN"});
        r15.A02("BA", new String[]{"BAM"});
        r15.A02("BB", new String[]{"BBD"});
        r15.A02("BD", new String[]{"BDT"});
        r15.A02("BE", new String[]{"EUR"});
        r15.A02("BF", new String[]{"XOF"});
        r15.A02("BG", new String[]{"BGN"});
        r15.A02("BH", new String[]{"BHD"});
        r15.A02("BI", new String[]{"BIF"});
        r15.A02("BJ", new String[]{"XOF"});
        r15.A02("BL", new String[]{"EUR"});
        r15.A02("BM", new String[]{"BMD"});
        r15.A02("BN", new String[]{"BND"});
        r15.A02("BO", new String[]{"BOB"});
        r15.A02("BQ", new String[]{"USD"});
        r15.A02("BR", new String[]{"BRL"});
        r15.A02("BS", new String[]{"BSD"});
        r15.A02("BT", new String[]{"BTN", "INR"});
        r15.A02("BV", new String[]{"NOK"});
        r15.A02("BW", new String[]{"BWP"});
        r15.A02("BY", new String[]{"BYN"});
        r15.A02("BZ", new String[]{"BZD"});
        r15.A02("CA", new String[]{"CAD"});
        r15.A02("CC", new String[]{"AUD"});
        r15.A02("CD", new String[]{"CDF"});
        r15.A02("CF", new String[]{"XAF"});
        r15.A02("CG", new String[]{"XAF"});
        r15.A02("CH", new String[]{"CHF"});
        r15.A02("CI", new String[]{"XOF"});
        r15.A02("CK", new String[]{"NZD"});
        r15.A02("CL", new String[]{"CLP"});
        r15.A02("CM", new String[]{"XAF"});
        r15.A02("CN", new String[]{"CNY"});
        r15.A02("CO", new String[]{"COP"});
        r15.A02("CR", new String[]{"CRC"});
        r15.A02("CU", new String[]{"CUP", "CUC"});
        r15.A02("CV", new String[]{"CVE"});
        r15.A02("CW", new String[]{"ANG"});
        r15.A02("CX", new String[]{"AUD"});
        r15.A02("CY", new String[]{"EUR"});
        r15.A02("CZ", new String[]{"CZK"});
        r15.A02("DE", new String[]{"EUR"});
        r15.A02("DG", new String[]{"USD"});
        r15.A02("DJ", new String[]{"DJF"});
        r15.A02("DK", new String[]{"DKK"});
        r15.A02("DM", new String[]{"XCD"});
        r15.A02("DO", new String[]{"DOP"});
        r15.A02("DZ", new String[]{"DZD"});
        r15.A02("EA", new String[]{"EUR"});
        r15.A02("EC", new String[]{"USD"});
        r15.A02("EE", new String[]{"EUR"});
        r15.A02("EG", new String[]{"EGP"});
        r15.A02("EH", new String[]{"MAD"});
        r15.A02("ER", new String[]{"ERN"});
        r15.A02("ES", new String[]{"EUR"});
        r15.A02("ET", new String[]{"ETB"});
        r15.A02("EU", new String[]{"EUR"});
        r15.A02("FI", new String[]{"EUR"});
        r15.A02("FJ", new String[]{"FJD"});
        r15.A02("FK", new String[]{"FKP"});
        r15.A02("FM", new String[]{"USD"});
        r15.A02("FO", new String[]{"DKK"});
        r15.A02("FR", new String[]{"EUR"});
        r15.A02("GA", new String[]{"XAF"});
        r15.A02("GB", new String[]{"GBP"});
        r15.A02("GD", new String[]{"XCD"});
        r15.A02("GE", new String[]{"GEL"});
        r15.A02("GF", new String[]{"EUR"});
        r15.A02("GG", new String[]{"GBP"});
        r15.A02("GH", new String[]{"GHS"});
        r15.A02("GI", new String[]{"GIP"});
        r15.A02("GL", new String[]{"DKK"});
        r15.A02("GM", new String[]{"GMD"});
        r15.A02("GN", new String[]{"GNF"});
        r15.A02("GP", new String[]{"EUR"});
        r15.A02("GQ", new String[]{"XAF"});
        r15.A02("GR", new String[]{"EUR"});
        r15.A02("GS", new String[]{"GBP"});
        r15.A02("GT", new String[]{"GTQ"});
        r15.A02("GU", new String[]{"USD"});
        r15.A02("GW", new String[]{"XOF"});
        r15.A02("GY", new String[]{"GYD"});
        r15.A02("HK", new String[]{"HKD"});
        r15.A02("HM", new String[]{"AUD"});
        r15.A02("HN", new String[]{"HNL"});
        r15.A02("HR", new String[]{"HRK"});
        r15.A02("HT", new String[]{"HTG", "USD"});
        r15.A02("HU", new String[]{"HUF"});
        r15.A02("IC", new String[]{"EUR"});
        r15.A02("ID", new String[]{"IDR"});
        r15.A02("IE", new String[]{"EUR"});
        r15.A02("IL", new String[]{"ILS"});
        r15.A02("IM", new String[]{"GBP"});
        r15.A02("IN", new String[]{"INR"});
        r15.A02("IO", new String[]{"USD"});
        r15.A02("IQ", new String[]{"IQD"});
        r15.A02("IR", new String[]{"IRR"});
        r15.A02("IS", new String[]{"ISK"});
        r15.A02("IT", new String[]{"EUR"});
        r15.A02("JE", new String[]{"GBP"});
        r15.A02("JM", new String[]{"JMD"});
        r15.A02("JO", new String[]{"JOD"});
        r15.A02("JP", new String[]{"JPY"});
        r15.A02("KE", new String[]{"KES"});
        r15.A02("KG", new String[]{"KGS"});
        r15.A02("KH", new String[]{"KHR"});
        r15.A02("KI", new String[]{"AUD"});
        r15.A02("KM", new String[]{"KMF"});
        r15.A02("KN", new String[]{"XCD"});
        r15.A02("KP", new String[]{"KPW"});
        r15.A02("KR", new String[]{"KRW"});
        r15.A02("KW", new String[]{"KWD"});
        r15.A02("KY", new String[]{"KYD"});
        r15.A02("KZ", new String[]{"KZT"});
        r15.A02("LA", new String[]{"LAK"});
        r15.A02("LB", new String[]{"LBP"});
        r15.A02("LC", new String[]{"XCD"});
        r15.A02("LI", new String[]{"CHF"});
        r15.A02("LK", new String[]{"LKR"});
        r15.A02("LR", new String[]{"LRD"});
        r15.A02("LS", new String[]{"ZAR", "LSL"});
        r15.A02("LT", new String[]{"EUR"});
        r15.A02("LU", new String[]{"EUR"});
        r15.A02("LV", new String[]{"EUR"});
        r15.A02("LY", new String[]{"LYD"});
        r15.A02("MA", new String[]{"MAD"});
        r15.A02("MC", new String[]{"EUR"});
        r15.A02("MD", new String[]{"MDL"});
        r15.A02("ME", new String[]{"EUR"});
        r15.A02("MF", new String[]{"EUR"});
        r15.A02("MG", new String[]{"MGA"});
        r15.A02("MH", new String[]{"USD"});
        r15.A02("MK", new String[]{"MKD"});
        r15.A02("ML", new String[]{"XOF"});
        r15.A02("MM", new String[]{"MMK"});
        r15.A02("MN", new String[]{"MNT"});
        r15.A02("MO", new String[]{"MOP"});
        r15.A02("MP", new String[]{"USD"});
        r15.A02("MQ", new String[]{"EUR"});
        r15.A02("MR", new String[]{"MRU"});
        r15.A02("MS", new String[]{"XCD"});
        r15.A02("MT", new String[]{"EUR"});
        r15.A02("MU", new String[]{"MUR"});
        r15.A02("MV", new String[]{"MVR"});
        r15.A02("MW", new String[]{"MWK"});
        r15.A02("MX", new String[]{"MXN"});
        r15.A02("MY", new String[]{"MYR"});
        r15.A02("MZ", new String[]{"MZN"});
        r15.A02("NA", new String[]{"NAD", "ZAR"});
        r15.A02("NC", new String[]{"XPF"});
        r15.A02("NE", new String[]{"XOF"});
        r15.A02("NF", new String[]{"AUD"});
        r15.A02("NG", new String[]{"NGN"});
        r15.A02("NI", new String[]{"NIO"});
        r15.A02("NL", new String[]{"EUR"});
        r15.A02("NO", new String[]{"NOK"});
        r15.A02("NP", new String[]{"NPR"});
        r15.A02("NR", new String[]{"AUD"});
        r15.A02("NU", new String[]{"NZD"});
        r15.A02("NZ", new String[]{"NZD"});
        r15.A02("OM", new String[]{"OMR"});
        r15.A02("PA", new String[]{"PAB", "USD"});
        r15.A02("PE", new String[]{"PEN"});
        r15.A02("PF", new String[]{"XPF"});
        r15.A02("PG", new String[]{"PGK"});
        r15.A02("PH", new String[]{"PHP"});
        r15.A02("PK", new String[]{"PKR"});
        r15.A02("PL", new String[]{"PLN"});
        r15.A02("PM", new String[]{"EUR"});
        r15.A02("PN", new String[]{"NZD"});
        r15.A02("PR", new String[]{"USD"});
        r15.A02("PS", new String[]{"ILS", "JOD"});
        r15.A02("PT", new String[]{"EUR"});
        r15.A02("PW", new String[]{"USD"});
        r15.A02("PY", new String[]{"PYG"});
        r15.A02("QA", new String[]{"QAR"});
        r15.A02("RE", new String[]{"EUR"});
        r15.A02("RO", new String[]{"RON"});
        r15.A02("RS", new String[]{"RSD"});
        r15.A02("RU", new String[]{"RUB"});
        r15.A02("RW", new String[]{"RWF"});
        r15.A02("SA", new String[]{"SAR"});
        r15.A02("SB", new String[]{"SBD"});
        r15.A02("SC", new String[]{"SCR"});
        r15.A02("SD", new String[]{"SDG"});
        r15.A02("SE", new String[]{"SEK"});
        r15.A02("SG", new String[]{"SGD"});
        r15.A02("SH", new String[]{"SHP"});
        r15.A02("SI", new String[]{"EUR"});
        r15.A02("SJ", new String[]{"NOK"});
        r15.A02("SK", new String[]{"EUR"});
        r15.A02("SL", new String[]{"SLL"});
        r15.A02("SM", new String[]{"EUR"});
        r15.A02("SN", new String[]{"XOF"});
        r15.A02("SO", new String[]{"SOS"});
        r15.A02("SR", new String[]{"SRD"});
        r15.A02("SS", new String[]{"SSP"});
        r15.A02("ST", new String[]{"STN"});
        r15.A02("SV", new String[]{"USD"});
        r15.A02("SX", new String[]{"ANG"});
        r15.A02("SY", new String[]{"SYP"});
        r15.A02("SZ", new String[]{"SZL"});
        r15.A02("TA", new String[]{"GBP"});
        r15.A02("TC", new String[]{"USD"});
        r15.A02("TD", new String[]{"XAF"});
        r15.A02("TF", new String[]{"EUR"});
        r15.A02("TG", new String[]{"XOF"});
        r15.A02("TH", new String[]{"THB"});
        r15.A02("TJ", new String[]{"TJS"});
        r15.A02("TK", new String[]{"NZD"});
        r15.A02("TL", new String[]{"USD"});
        r15.A02("TM", new String[]{"TMT"});
        r15.A02("TN", new String[]{"TND"});
        r15.A02("TO", new String[]{"TOP"});
        r15.A02("TR", new String[]{"TRY"});
        r15.A02("TT", new String[]{"TTD"});
        r15.A02("TV", new String[]{"AUD"});
        r15.A02("TW", new String[]{"TWD"});
        r15.A02("TZ", new String[]{"TZS"});
        r15.A02("UA", new String[]{"UAH"});
        r15.A02("UG", new String[]{"UGX"});
        r15.A02("UM", new String[]{"USD"});
        r15.A02("US", new String[]{"USD"});
        r15.A02("UY", new String[]{"UYU"});
        r15.A02("UZ", new String[]{"UZS"});
        r15.A02("VA", new String[]{"EUR"});
        r15.A02("VC", new String[]{"XCD"});
        r15.A02("VE", new String[]{"VES"});
        r15.A02("VG", new String[]{"USD"});
        r15.A02("VI", new String[]{"USD"});
        r15.A02("VN", new String[]{"VND"});
        r15.A02("VU", new String[]{"VUV"});
        r15.A02("WF", new String[]{"XPF"});
        r15.A02("WS", new String[]{"WST"});
        r15.A02("XK", new String[]{"EUR"});
        r15.A02("YE", new String[]{"YER"});
        r15.A02("YT", new String[]{"EUR"});
        r15.A02("ZA", new String[]{"ZAR"});
        r15.A02("ZM", new String[]{"ZMW"});
        r15.A02("ZW", new String[]{"USD"});
        HashMap hashMap = new HashMap();
        A01 = hashMap;
        hashMap.put("ADP", 0);
        HashMap hashMap2 = A01;
        hashMap2.put("AFN", 0);
        hashMap2.put("ALL", 0);
        hashMap2.put("BHD", 3);
        hashMap2.put("BIF", 0);
        hashMap2.put("BYR", 0);
        hashMap2.put("CLF", 4);
        hashMap2.put("CLP", 0);
        hashMap2.put("DJF", 0);
        hashMap2.put("ESP", 0);
        hashMap2.put("GNF", 0);
        hashMap2.put("IQD", 0);
        hashMap2.put("IRR", 0);
        hashMap2.put("ISK", 0);
        hashMap2.put("ITL", 0);
        hashMap2.put("JOD", 3);
        hashMap2.put("JPY", 0);
        hashMap2.put("KMF", 0);
        hashMap2.put("KPW", 0);
        hashMap2.put("KRW", 0);
        hashMap2.put("KWD", 3);
        hashMap2.put("LAK", 0);
        hashMap2.put("LBP", 0);
        hashMap2.put("LUF", 0);
        hashMap2.put("LYD", 3);
        hashMap2.put("MGA", 0);
        hashMap2.put("MGF", 0);
        hashMap2.put("MMK", 0);
        hashMap2.put("MRO", 0);
        hashMap2.put("OMR", 3);
        hashMap2.put("PYG", 0);
        hashMap2.put("RSD", 0);
        hashMap2.put("RWF", 0);
        hashMap2.put("SLL", 0);
        hashMap2.put("SOS", 0);
        hashMap2.put("STD", 0);
        hashMap2.put("SYP", 0);
        hashMap2.put("TMM", 0);
        hashMap2.put("TND", 3);
        hashMap2.put("TRL", 0);
        hashMap2.put("UGX", 0);
        hashMap2.put("UYI", 0);
        hashMap2.put("UYW", 4);
        hashMap2.put("VND", 0);
        hashMap2.put("VUV", 0);
        hashMap2.put("XAF", 0);
        hashMap2.put("XOF", 0);
        hashMap2.put("XPF", 0);
        hashMap2.put("YER", 0);
        hashMap2.put("ZMK", 0);
        hashMap2.put("ZWD", 0);
        HashMap hashMap3 = new HashMap();
        A02 = hashMap3;
        hashMap3.put("AED", 12);
        HashMap hashMap4 = A02;
        hashMap4.put("AFN", 13);
        hashMap4.put("ALL", 14);
        hashMap4.put("AMD", 15);
        hashMap4.put("ANG", 16);
        hashMap4.put("AOA", 17);
        hashMap4.put("ARS", 18);
        hashMap4.put("AUD", 19);
        hashMap4.put("AWG", 20);
        hashMap4.put("AZN", 21);
        hashMap4.put("BAM", 22);
        hashMap4.put("BBD", 23);
        hashMap4.put("BDT", 24);
        hashMap4.put("BGN", 25);
        hashMap4.put("BHD", 26);
        hashMap4.put("BIF", 27);
        hashMap4.put("BMD", 28);
        hashMap4.put("BND", 29);
        hashMap4.put("BOB", 30);
        hashMap4.put("BRL", 31);
        hashMap4.put("BSD", 32);
        hashMap4.put("BTN", 33);
        hashMap4.put("BWP", 34);
        hashMap4.put("BYN", 35);
        hashMap4.put("BZD", 36);
        hashMap4.put("CAD", 37);
        hashMap4.put("CDF", 38);
        hashMap4.put("CHF", 39);
        hashMap4.put("CLP", 40);
        hashMap4.put("CNY", 41);
        hashMap4.put("COP", 42);
        hashMap4.put("CRC", 43);
        hashMap4.put("CUC", 44);
        hashMap4.put("CUP", 45);
        hashMap4.put("CVE", 46);
        hashMap4.put("CZK", 47);
        hashMap4.put("DJF", 48);
        hashMap4.put("DKK", 49);
        hashMap4.put("DOP", 50);
        hashMap4.put("DZD", 51);
        hashMap4.put("EGP", 52);
        hashMap4.put("ERN", 53);
        hashMap4.put("ETB", 54);
        hashMap4.put("EUR", 55);
        hashMap4.put("FJD", 56);
        hashMap4.put("FKP", 57);
        hashMap4.put("GBP", 58);
        hashMap4.put("GEL", 59);
        hashMap4.put("GHS", 60);
        hashMap4.put("GIP", 61);
        hashMap4.put("GMD", 62);
        hashMap4.put("GNF", 63);
        hashMap4.put("GTQ", 64);
        hashMap4.put("GYD", 65);
        hashMap4.put("HKD", 66);
        hashMap4.put("HNL", 67);
        hashMap4.put("HRK", 68);
        hashMap4.put("HTG", 69);
        hashMap4.put("HUF", 70);
        hashMap4.put("IDR", 71);
        hashMap4.put("ILS", 72);
        hashMap4.put("INR", 73);
        hashMap4.put("IQD", 74);
        hashMap4.put("IRR", 75);
        hashMap4.put("ISK", 76);
        hashMap4.put("JMD", 77);
        hashMap4.put("JOD", 78);
        hashMap4.put("JPY", 79);
        hashMap4.put("KES", 80);
        hashMap4.put("KGS", 81);
        hashMap4.put("KHR", 82);
        hashMap4.put("KMF", 83);
        hashMap4.put("KPW", 84);
        hashMap4.put("KRW", 85);
        hashMap4.put("KWD", 86);
        hashMap4.put("KYD", 87);
        hashMap4.put("KZT", 88);
        hashMap4.put("LAK", 89);
        hashMap4.put("LBP", 90);
        hashMap4.put("LKR", 91);
        hashMap4.put("LRD", 92);
        hashMap4.put("LSL", 93);
        hashMap4.put("LYD", 94);
        hashMap4.put("MAD", 95);
        hashMap4.put("MDL", 96);
        hashMap4.put("MGA", 97);
        hashMap4.put("MKD", 98);
        hashMap4.put("MMK", 99);
        hashMap4.put("MNT", 100);
        hashMap4.put("MOP", 101);
        hashMap4.put("MRU", 102);
        hashMap4.put("MUR", 103);
        hashMap4.put("MVR", 104);
        hashMap4.put("MWK", 105);
        hashMap4.put("MXN", 106);
        hashMap4.put("MYR", 107);
        hashMap4.put("MZN", Integer.valueOf((int) AnonymousClass0PW.A03));
        hashMap4.put("NAD", 109);
        hashMap4.put("NGN", 110);
        hashMap4.put("NIO", 111);
        hashMap4.put("NOK", 112);
        hashMap4.put("NPR", 113);
        hashMap4.put("NZD", 114);
        hashMap4.put("OMR", 115);
        hashMap4.put("PAB", 116);
        hashMap4.put("PEN", 117);
        hashMap4.put("PGK", 118);
        hashMap4.put("PHP", 119);
        hashMap4.put("PKR", 120);
        hashMap4.put("PLN", 121);
        hashMap4.put("PYG", 122);
        hashMap4.put("QAR", 123);
        hashMap4.put("RON", 124);
        hashMap4.put("RSD", 125);
        hashMap4.put("RUB", 126);
        hashMap4.put("RWF", 127);
        hashMap4.put("SAR", 128);
        hashMap4.put("SBD", 129);
        hashMap4.put("SCR", 130);
        hashMap4.put("SDG", 131);
        hashMap4.put("SEK", 132);
        hashMap4.put("SGD", 133);
        hashMap4.put("SHP", 134);
        hashMap4.put("SLL", 135);
        hashMap4.put("SOS", 136);
        hashMap4.put("SRD", 137);
        hashMap4.put("SSP", 138);
        hashMap4.put("STN", 139);
        hashMap4.put("SYP", 140);
        hashMap4.put("SZL", 141);
        hashMap4.put("THB", 142);
        hashMap4.put("TJS", 143);
        hashMap4.put("TMT", Integer.valueOf((int) MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT));
        hashMap4.put("TND", 145);
        hashMap4.put("TOP", 146);
        hashMap4.put("TRY", 147);
        hashMap4.put("TTD", 148);
        hashMap4.put("TWD", 149);
        hashMap4.put("TZS", 150);
        hashMap4.put("UAH", 151);
        hashMap4.put("UGX", 152);
        hashMap4.put("USD", 153);
        hashMap4.put("UYU", 154);
        hashMap4.put("UZS", 155);
        hashMap4.put("VES", 156);
        hashMap4.put("VND", 157);
        hashMap4.put("VUV", 158);
        hashMap4.put("WST", 159);
        hashMap4.put("XAF", 160);
        hashMap4.put("XCD", 161);
        hashMap4.put("XOF", 162);
        hashMap4.put("XPF", 163);
        hashMap4.put("YER", 164);
        hashMap4.put("ZAR", 165);
        hashMap4.put("ZMW", 166);
    }
}
