package X;

import java.util.Arrays;
import java.util.List;

/* renamed from: X.0Oh  reason: invalid class name and case insensitive filesystem */
public abstract class AbstractC05380Oh {
    public static final AnonymousClass03V A00;
    public static final AnonymousClass05W A01;
    public static final AnonymousClass05W A02;
    public static final AnonymousClass05W A03;
    public static final AnonymousClass0GF A04;

    static {
        AnonymousClass05W r1 = new AnonymousClass05W(23);
        A03 = r1;
        r1.put("ar", (char) 1593);
        AnonymousClass05W r12 = A03;
        r12.put("az", (char) 399);
        r12.put("bn", (char) 2437);
        r12.put("zh-Hans", (char) 35831);
        r12.put("zh-Hant", (char) 35531);
        r12.put("hr", (char) 273);
        r12.put("gu", (char) 2693);
        r12.put("hi", (char) 2308);
        r12.put("kn", (char) 3205);
        r12.put("kk", (char) 1201);
        r12.put("lo", (char) 3713);
        r12.put("mk", (char) 1107);
        r12.put("ml", (char) 3333);
        r12.put("mr", (char) 2418);
        r12.put("fa", (char) 1740);
        r12.put("pa", (char) 2576);
        r12.put("ro", (char) 539);
        r12.put("sr", (char) 1115);
        r12.put("ta", (char) 2949);
        r12.put("te", (char) 3077);
        r12.put("th", (char) 3585);
        r12.put("uk", (char) 1111);
        r12.put("ur", (char) 1746);
        AnonymousClass05W r2 = new AnonymousClass05W(14);
        A02 = r2;
        r2.put("ar", AbstractC002201f.A0B(1632));
        AnonymousClass05W r22 = A02;
        r22.put("bn", AbstractC002201f.A0B(2534));
        r22.put("fa", AbstractC002201f.A0B(1776));
        r22.put("gu", AbstractC002201f.A0B(2790));
        r22.put("hi", AbstractC002201f.A0B(2406));
        r22.put("kn", AbstractC002201f.A0B(3302));
        r22.put("lo", AbstractC002201f.A0B(3792));
        r22.put("ml", AbstractC002201f.A0B(3430));
        r22.put("mr", AbstractC002201f.A0B(2406));
        r22.put("pa", AbstractC002201f.A0B(2662));
        r22.put("ta", AbstractC002201f.A0B(3046));
        r22.put("te", AbstractC002201f.A0B(3174));
        r22.put("th", AbstractC002201f.A0B(3664));
        r22.put("ur", AbstractC002201f.A0B(1776));
        AnonymousClass0GF r5 = new AnonymousClass0GF(47);
        A04 = r5;
        r5.A03("AF", new String[]{"fa-AF", "en-GB"});
        AnonymousClass0GF r4 = A04;
        r4.A03("AL", new String[]{"sq-AL", "en-GB"});
        r4.A03("DZ", new String[]{"ar-DZ", "fr-DZ"});
        r4.A03("AD", new String[]{"ca-AD", "es-ES", "pt-PT", "fr-FR"});
        r4.A03("AZ", new String[]{"az-AZ", "ru-RU", "tr-TR"});
        r4.A03("BH", new String[]{"ar-BH", "en-GB"});
        r4.A03("BD", new String[]{"bn-BD", "en-GB"});
        r4.A03("BA", new String[]{"hr-BA", "sr-BA"});
        r4.A03("BN", new String[]{"ms-BN", "en-GB", "zh-CN", "zh-TW"});
        r4.A03("BI", new String[]{"en-BI", "fr-BI", "sw-TZ"});
        r4.A03("TD", new String[]{"fr-TD", "ar-TD"});
        r4.A03("KM", new String[]{"fr-KM", "en-GB", "ar-KM"});
        r4.A03("CD", new String[]{"fr-CD", "sw-CD"});
        r4.A03("DJ", new String[]{"fr-DJ", "en-GB", "ar-DJ"});
        r4.A03("ER", new String[]{"en-ER", "ar-ER"});
        r4.A03("IN", new String[]{"en-IN", "hi-IN", "bn-IN", "pa-IN", "te-IN", "mr-IN", "ta-IN", "ur-IN", "gu-IN", "kn-IN", "ml-IN"});
        r4.A03("IE", new String[]{"en-IE", "ga-IE"});
        r4.A03("IL", new String[]{"iw-IL", "ar-IL", "en-IL", "ru-RU"});
        r4.A03("KZ", new String[]{"kk-KZ", "ru-KZ"});
        r4.A03("KE", new String[]{"en-KE", "sw-KE"});
        r4.A03("XK", new String[]{"sq-XK", "sr-XK", "hr-HR"});
        r4.A03("KW", new String[]{"ar-KW", "en-GB"});
        r4.A03("LA", new String[]{"lo-LA", "th-TH", "en-GB"});
        r4.A03("LB", new String[]{"ar-LB", "en-GB", "fr-FR"});
        r4.A03("MK", new String[]{"mk-MK", "sq-MK", "tr-TR", "hr-HR", "sr-RS"});
        r4.A03("MW", new String[]{"en-MW", "sw-TZ"});
        r4.A03("MY", new String[]{"ms-MY", "en-MY", "zh-CN", "zh-TW", "ta-MY"});
        r4.A03("MR", new String[]{"ar-MR", "fr-MR"});
        r4.A03("MD", new String[]{"ro-MD", "ru-MD"});
        r4.A03("MA", new String[]{"ar-MA", "fr-MA"});
        r4.A03("OM", new String[]{"ar-OM", "en-GB"});
        r4.A03("PK", new String[]{"en-PK", "ur-PK"});
        r4.A03("PH", new String[]{"en-PH", "fil-PH", "es-PH", "ar-EG"});
        r4.A03("QA", new String[]{"ar-QA", "en-GB"});
        r4.A03("RW", new String[]{"en-RW", "fr-RW", "sw-TZ"});
        r4.A03("SA", new String[]{"ar-SA", "en-GB"});
        r4.A03("SO", new String[]{"en-GB", "ar-SO"});
        r4.A03("SS", new String[]{"en-SS", "ar-SS"});
        r4.A03("SI", new String[]{"sl-SI", "en-SI", "hr-HR", "it-IT", "hu-HU", "sr-RS"});
        r4.A03("TZ", new String[]{"en-TZ", "sw-TZ"});
        r4.A03("TN", new String[]{"ar-TN", "fr-TN"});
        r4.A03("UG", new String[]{"en-UG", "sw-UG"});
        r4.A03("UA", new String[]{"uk-UA", "ru-UA"});
        r4.A03("AE", new String[]{"ar-AE", "en-GB"});
        r4.A03("GB", new String[]{"en-GB", "ga-IE"});
        r4.A03("US", new String[]{"en-US", "es-LA", "pt-BR", "ar-AE", "zh-CN", "fr-FR", "ru-RU", "vi-VN", "ko-KR"});
        r4.A03("UZ", new String[]{"uz-UZ", "ru-RU"});
        r4.A03("QQ", new String[]{"az-AZ", "ca-ES", "en-US", "es-ES", "fil-PH", "fr-FR", "ga-IE", "hr-HR", "it-IT", "sw-TZ", "uz-UZ", "hu-HU", "ms-MY", "sq-AL", "sl-SI", "tr-TR", "kk-KZ", "ru-RU", "sr-RS", "uk-UA", "iw-IL", "ur-PK", "fa-IR", "ar-EG", "hi-IN", "bn-BD", "pa-IN", "te-IN", "mr-IN", "ta-IN", "gu-IN", "kn-IN", "ml-IN", "th-TH", "lo-LA", "zh-CN", "zh-TW"});
        AnonymousClass05W r42 = new AnonymousClass05W(59);
        A01 = r42;
        r42.put("af", "Afrikaans");
        AnonymousClass05W r15 = A01;
        r15.put("sq", "Shqip");
        r15.put("ar", "العربية");
        r15.put("az", "Azərbaycan dili");
        r15.put("bn", "বাংলা");
        r15.put("bg", "Български");
        r15.put("ca", "Català");
        r15.put("zh-Hans", "简体中文");
        r15.put("zh-Hant", "繁體中文");
        r15.put("hr", "Hrvatski");
        r15.put("cs", "Čeština");
        r15.put("nl", "Nederlands");
        r15.put("en", "English");
        r15.put("de", "Deutsch");
        r15.put("el", "Ελληνικά");
        r15.put("et", "Eesti");
        r15.put("fil", "Filipino");
        r15.put("fi", "Suomi");
        r15.put("fr", "Français");
        r15.put("gu", "ગુજરાતી");
        r15.put("iw", "עברית");
        r15.put("hi", "हिन्दी");
        r15.put("hu", "Magyar");
        r15.put("in", "Bahasa Indonesia");
        r15.put("ga", "Gaeilge");
        r15.put("it", "Italiano");
        r15.put("ja", "日本語");
        r15.put("kn", "ಕನ್ನಡ");
        r15.put("kk", "Қазақ тілі");
        r15.put("ko", "한국어");
        r15.put("lo", "ລາວ");
        r15.put("lv", "Latviešu");
        r15.put("lt", "Lietuvių");
        r15.put("mk", "Македонски");
        r15.put("ms", "Melayu");
        r15.put("ml", "മലയാളം");
        r15.put("mr", "मराठी");
        r15.put("nb", "Norsk bokmål");
        r15.put("fa", "فارسی");
        r15.put("pl", "Polski");
        r15.put("pt", "Português");
        r15.put("pa", "ਪੰਜਾਬੀ");
        r15.put("ro", "Română");
        r15.put("ru", "Русский");
        r15.put("sr", "Српски");
        r15.put("sk", "Slovenčina");
        r15.put("sl", "Slovenščina");
        r15.put("es", "Español");
        r15.put("sw", "Kiswahili");
        r15.put("sv", "Svenska");
        r15.put("tl", "Filipino");
        r15.put("ta", "தமிழ்");
        r15.put("te", "తెలుగు");
        r15.put("th", "ไทย");
        r15.put("tr", "Türkçe");
        r15.put("uk", "Українська");
        r15.put("ur", "اردو");
        r15.put("uz", "O‘zbek");
        r15.put("vi", "Tiếng Việt");
        List asList = Arrays.asList("sq", "ar", "az", "bn", "ca", "zh-Hans", "zh-Hant", "hr", "en", "fil", "fr", "gu", "iw", "hi", "hu", "ga", "it", "kn", "kk", "ko", "lo", "mk", "ms", "ml", "mr", "fa", "pt", "pa", "ro", "ru", "sr", "sl", "es", "sw", "tl", "ta", "te", "tr", "uk", "ur", "uz", "vi");
        AnonymousClass03V r0 = new AnonymousClass03V(0);
        if (asList != null) {
            r0.addAll(asList);
        }
        A00 = r0;
    }
}
