package X;

import android.text.TextUtils;
import java.util.Arrays;

/* renamed from: X.0Og  reason: invalid class name and case insensitive filesystem */
public abstract class AbstractC05370Og {
    public static final String A00 = TextUtils.join(", ", Arrays.asList("key_from_me", "key_id", "status", "needs_push", "data", "timestamp", "media_url", "media_mime_type", "media_wa_type", "media_size", "media_name", "media_caption", "media_hash", "media_duration", "origin", "latitude", "longitude", "thumb_image", "remote_resource", "raw_data", "recipient_count", "participant_hash", "starred", "quoted_row_id", "mentioned_jids", "multicast_id", "edit_version", "receipt_server_timestamp", "media_enc_hash", "payment_transaction_id", "forwarded", "preview_type", "received_timestamp", "lookup_tables", "_id"));
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;
    public static final String A0J;
    public static final String A0K;
    public static final String A0L;
    public static final String A0M;
    public static final String A0N;
    public static final String A0O;
    public static final String A0P;
    public static final String A0Q;
    public static final String A0R;
    public static final String A0S;
    public static final String A0T;
    public static final String A0U;
    public static final String A0V;
    public static final String A0W;
    public static final String A0X;
    public static final String A0Y;
    public static final String A0Z;
    public static final String A0a;
    public static final String A0b;
    public static final String A0c;
    public static final String A0d;
    public static final String A0e;
    public static final String A0f;
    public static final String A0g;
    public static final String A0h;
    public static final String A0i;
    public static final String A0j;
    public static final String A0k;
    public static final String A0l;
    public static final String A0m;
    public static final String A0n;
    public static final String A0o;
    public static final String A0p;
    public static final String A0q;
    public static final String A0r = AnonymousClass008.A0Q(new StringBuilder(), A05, " ORDER BY ", "_id", " DESC LIMIT ?");
    public static final String A0s;
    public static final String A0t;
    public static final String A0u;
    public static final String A0v;
    public static final String A0w;
    public static final String A0x;
    public static final String A0y;
    public static final String A0z;
    public static final String A10;
    public static final String A11;
    public static final String A12;
    public static final String A13;
    public static final String A14;
    public static final String A15;
    public static final String A16;
    public static final String A17;
    public static final String A18;
    public static final String A19;
    public static final String A1A;
    public static final String A1B;
    public static final String A1C;
    public static final String A1D;
    public static final String A1E;
    public static final String A1F;
    public static final String A1G;
    public static final String A1H;
    public static final String A1I;
    public static final String A1J;
    public static final String A1K;
    public static final String A1L;
    public static final String A1M;
    public static final String A1N;

    static {
        String join = TextUtils.join(", ", Arrays.asList("sort_id", "from_me", "key_id", "status", "broadcast", "data", "timestamp", "media_url", "media_mime_type", "message_type", "media_size", "media_name", "media_caption", "media_hash", "media_duration", "origin", "latitude", "longitude", "thumb_image", "raw_data", "recipient_count", "participant_hash", "starred", "quoted_row_id", "mentioned_jids", "multicast_id", "edit_version", "receipt_server_timestamp", "media_enc_hash", "payment_transaction_id", "origination_flags", "preview_type", "received_timestamp", "_id", "text_data", "lookup_tables", "sender_jid_row_id", "sender_jid_raw_string", "chat_row_id", "table_version"));
        A11 = join;
        StringBuilder A0S2 = AnonymousClass008.A0S("   SELECT ");
        AnonymousClass008.A1Y(A0S2, join, " FROM ", "available_message_view", " WHERE ");
        String A0O2 = AnonymousClass008.A0O(A0S2, "chat_row_id", " = ?");
        A1B = A0O2;
        A05 = AnonymousClass008.A0P(new StringBuilder(), A0O2, " AND ", "(message_type != '8')");
        StringBuilder A0S3 = AnonymousClass008.A0S("   SELECT ");
        AnonymousClass008.A1Y(A0S3, join, ", ", "chat_row_id", " FROM ");
        AnonymousClass008.A1Y(A0S3, "available_message_view", " WHERE ", "_id >= ? ", " AND ");
        AnonymousClass008.A1Y(A0S3, "_id < ? ", "AND (expire_timestamp IS NULL  OR expire_timestamp>= ?) ", " ORDER BY ", "_id DESC");
        A0S3.append(" LIMIT ? ");
        A1D = A0S3.toString();
        String join2 = TextUtils.join(", ", Arrays.asList("messages_quotes._id AS sort_id", "messages_quotes.key_from_me AS from_me", "messages_quotes.key_id AS key_id", "messages_quotes.status AS status", "messages_quotes.needs_push AS broadcast", "messages_quotes.data AS data", "messages_quotes.timestamp AS timestamp", "messages_quotes.media_url AS media_url", "messages_quotes.media_mime_type AS media_mime_type", "messages_quotes.media_wa_type AS message_type", "messages_quotes.media_size AS media_size", "messages_quotes.media_name AS media_name", "messages_quotes.media_caption AS media_caption", "messages_quotes.media_hash AS media_hash", "messages_quotes.media_duration AS media_duration", "messages_quotes.origin AS origin", "messages_quotes.latitude AS latitude", "messages_quotes.longitude AS longitude", "messages_quotes.thumb_image AS thumb_image", "messages_quotes.raw_data AS raw_data", "messages_quotes.recipient_count AS recipient_count", "messages_quotes.participant_hash AS participant_hash", "messages_quotes.starred AS starred", "messages_quotes.quoted_row_id AS quoted_row_id", "messages_quotes.mentioned_jids AS mentioned_jids", "messages_quotes.multicast_id AS multicast_id", "messages_quotes.edit_version AS edit_version", "messages_quotes.receipt_server_timestamp AS receipt_server_timestamp", "messages_quotes.media_enc_hash AS media_enc_hash", "messages_quotes.payment_transaction_id AS payment_transaction_id", "messages_quotes.forwarded AS origination_flags", "messages_quotes.preview_type AS preview_type", "messages_quotes.received_timestamp AS received_timestamp", "messages_quotes._id AS _id", "'' AS text_data", "0 AS lookup_tables", "-1 AS sender_jid_row_id", "messages_quotes.remote_resource AS sender_jid_raw_string", "chat._id AS chat_row_id", "1 AS table_version"));
        A12 = join2;
        StringBuilder A0S4 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S4, join2, " FROM ", "messages_quotes", " JOIN ");
        AnonymousClass008.A1Y(A0S4, "jid AS chat_jid ON messages_quotes.key_remote_jid = chat_jid.raw_string", " JOIN ", "chat AS chat ON chat.jid_row_id = chat_jid._id", " WHERE ");
        A0S4.append("messages_quotes._id = ?");
        A0t = A0S4.toString();
        StringBuilder A0S5 = AnonymousClass008.A0S("SELECT ");
        String str = A11;
        AnonymousClass008.A1Y(A0S5, str, " FROM ", "available_message_view", " WHERE ");
        A0S5.append("_id = ?");
        A0j = A0S5.toString();
        A0i = AnonymousClass008.A0Q(AnonymousClass008.A0S("SELECT "), str, " FROM ", "message_view", " WHERE chat_row_id=? AND from_me=? AND key_id=?");
        StringBuilder A0S6 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S6, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S6, "chat_row_id = ?", " AND ", "from_me = ?", " AND ");
        A0S6.append("key_id = ?");
        A0k = A0S6.toString();
        String str2 = A1B;
        StringBuilder sb = new StringBuilder();
        sb.append("SELECT ");
        AnonymousClass008.A1Y(sb, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(sb, "chat_row_id", "=?", " ORDER BY ", "_id");
        sb.append(" DESC LIMIT 1");
        A10 = sb.toString();
        StringBuilder A0S7 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S7, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S7, "chat_row_id", " = ?", " AND ", "from_me");
        AnonymousClass008.A1Y(A0S7, " = 1", " AND ", "message_type", " = ");
        A0S7.append(7);
        A0S7.append(" AND ");
        A0S7.append("media_size");
        A0S7.append(" = ");
        A0S7.append(6);
        A0S7.append(" ORDER BY ");
        A0S7.append("_id");
        A0S7.append(" DESC LIMIT 1");
        A0H = A0S7.toString();
        StringBuilder sb2 = new StringBuilder();
        AnonymousClass008.A1Y(sb2, str2, " AND ", "message_type", " NOT IN ('");
        AnonymousClass008.A1O(sb2, 8, "', '", 10, "', '");
        AnonymousClass008.A1O(sb2, 7, "', '", 15, "', '");
        sb2.append(19);
        sb2.append("')");
        sb2.append(" AND ");
        sb2.append("from_me");
        A0I = AnonymousClass008.A0P(sb2, " = 0 ORDER BY ", "_id", " DESC LIMIT ?");
        StringBuilder A0S8 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S8, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S8, "chat_row_id", " = ? ", " AND ", "message_type");
        A0S8.append(" NOT IN ('");
        A0S8.append(8);
        A0S8.append("' , '");
        A0S8.append(10);
        AnonymousClass008.A1Y(A0S8, "')", " AND (", "from_me", " = 0");
        A0S8.append(" OR (");
        A0S8.append("message_type");
        A0S8.append(" = '");
        A0S8.append(7);
        A0S8.append("' AND ");
        A0S8.append("media_size");
        A0S8.append(" = ");
        A0S8.append(4);
        AnonymousClass008.A1Y(A0S8, " AND ", "media_duration", " = 1)", " OR (");
        A0S8.append("message_type");
        A0S8.append("=");
        A0S8.append(7);
        A0S8.append(" AND ");
        A0S8.append("media_size");
        A0S8.append(" = ");
        A0S8.append(12);
        A0S8.append(" AND ");
        AnonymousClass008.A1Y(A0S8, "media_duration", " = 1))", " ORDER BY ", "_id");
        A0S8.append(" DESC LIMIT ?");
        A0p = A0S8.toString();
        StringBuilder A0S9 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S9, str, " FROM ", "available_message_view AS message", " LEFT JOIN ");
        AnonymousClass008.A1Y(A0S9, "message_system", " AS message_system", " ON message_system.message_row_id = message._id", " LEFT JOIN ");
        AnonymousClass008.A1Y(A0S9, "message_system_group", " AS system_group", " ON message_system.message_row_id = system_group.message_row_id", " WHERE ");
        AnonymousClass008.A1Y(A0S9, "message.chat_row_id = ?", " AND ", "message.message_type NOT IN ('8' , '10')", " AND (");
        A0o = AnonymousClass008.A0P(A0S9, "message.from_me = 0 OR (message_system.action_type = 4 AND system_group.is_me_joined = 1) OR (message_system.action_type = 12 AND system_group.is_me_joined = 1))", " ORDER BY _id", " DESC LIMIT ?");
        StringBuilder A0S10 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S10, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S10, "chat_row_id", " = ? ", " AND ", "message_type");
        A0S10.append(" NOT IN ('");
        A0S10.append(8);
        A0S10.append("', '");
        A0S10.append(10);
        A0n = AnonymousClass008.A0Q(A0S10, "') ", " ORDER BY ", "_id", " DESC LIMIT ?");
        StringBuilder A0S11 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S11, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S11, "chat_row_id = ?", " AND ", "_id > ?", " AND ");
        A0h = AnonymousClass008.A0Q(A0S11, "_id <= ?", "ORDER BY ", "_id", " ASC LIMIT 1024");
        StringBuilder A0S12 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S12, str, " FROM ", "message_view", " WHERE ");
        A0w = AnonymousClass008.A0Q(A0S12, "chat_row_id = ?", " ORDER BY ", "_id", " ASC");
        StringBuilder A0S13 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S13, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S13, "chat_row_id = ?", " AND ", "(sender_jid_row_id = ? OR sender_jid_raw_string = ?) ", " ORDER BY ");
        A0S13.append("_id ASC");
        A1E = A0S13.toString();
        StringBuilder A0S14 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S14, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S14, "from_me = 1", " AND ", "chat_row_id = ?", " ORDER BY ");
        A1F = AnonymousClass008.A0O(A0S14, "_id", " ASC");
        StringBuilder A0S15 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S15, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S15, "chat_row_id = ?", " AND ", "(sender_jid_row_id = ? OR sender_jid_raw_string = ?)", " AND ");
        A0u = AnonymousClass008.A0P(A0S15, "_id < ? ", " ORDER BY _id DESC", " LIMIT ?");
        StringBuilder A0S16 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S16, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S16, "from_me = 1", " AND ", "chat_row_id = ?", " AND ");
        A0v = AnonymousClass008.A0P(A0S16, "_id < ? ", " ORDER BY _id DESC", " LIMIT ?");
        StringBuilder A0S17 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S17, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S17, "chat_row_id = ?", " AND ", "_id > ?", " ORDER BY ");
        A0S17.append("_id ASC");
        A0x = A0S17.toString();
        A0X = AnonymousClass008.A0Q(new StringBuilder(), str2, " AND ", "message_type = ?", " ORDER BY _id DESC");
        StringBuilder A0S18 = AnonymousClass008.A0S("SELECT ");
        A0S18.append(A00("message", str));
        A0S18.append(" FROM ");
        A0S18.append("message_media AS message_media");
        A0S18.append(" JOIN ");
        A0S18.append("available_message_view AS message");
        AnonymousClass008.A1Y(A0S18, " ON message_media.message_row_id = message._id", " WHERE ", "message_media.file_hash = ?", " AND ");
        A0W = AnonymousClass008.A0P(A0S18, "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " ORDER BY _id DESC", " LIMIT 1000");
        StringBuilder A0S19 = AnonymousClass008.A0S("SELECT ");
        A0S19.append(A00("message", str));
        A0S19.append(" FROM ");
        A0S19.append("message_media AS message_media");
        A0S19.append(" JOIN ");
        A0S19.append("available_message_view AS message");
        AnonymousClass008.A1Y(A0S19, " ON message_media.message_row_id = message._id", " WHERE ", "message_media.file_hash = ?", " AND ");
        A0V = AnonymousClass008.A0P(A0S19, "message.message_type = ?", " ORDER BY _id DESC", " LIMIT 1000");
        StringBuilder A0S20 = AnonymousClass008.A0S("SELECT message_media.*, ");
        A0S20.append(A00("message", "timestamp"));
        A0S20.append(",");
        A0S20.append(A00("message", "message_type"));
        A0S20.append(",");
        A0S20.append(A00("message", "media_url"));
        A0S20.append(" FROM ");
        A0S20.append("message_media AS message_media");
        AnonymousClass008.A1Y(A0S20, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " WHERE ");
        A0d = AnonymousClass008.A0Q(A0S20, "file_hash = ?", " AND ", "enc_file_hash IS NOT NULL", " ORDER BY message_row_id DESC");
        StringBuilder A0S21 = AnonymousClass008.A0S("SELECT message_media.*, ");
        A0S21.append(A00("message", "timestamp"));
        A0S21.append(",");
        A0S21.append(A00("message", "message_type"));
        A0S21.append(",");
        A0S21.append(A00("message", "media_url"));
        A0S21.append(" FROM ");
        A0S21.append("message_media AS message_media");
        AnonymousClass008.A1Y(A0S21, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " WHERE ");
        AnonymousClass008.A1Y(A0S21, "file_hash = ?", " AND ", "enc_file_hash IS NOT NULL", " AND ");
        A0c = AnonymousClass008.A0O(A0S21, "message.message_type = ?", " ORDER BY _id DESC");
        StringBuilder A0S22 = AnonymousClass008.A0S("SELECT message_media.*, ");
        A0S22.append(A00("message", "chat_row_id, from_me, key_id"));
        A0S22.append(" FROM ");
        A0S22.append("message_media AS message_media");
        A0S22.append(" JOIN ");
        A0S22.append("available_message_view AS message");
        AnonymousClass008.A1Y(A0S22, " ON message_media.message_row_id = message._id", " WHERE ", "file_hash = ?", " AND ");
        AnonymousClass008.A1Y(A0S22, "enc_file_hash = ?", " AND ", "message_type in ('3', '1' ) ", " ORDER BY _id DESC");
        A0S22.append(" LIMIT 10");
        A0e = A0S22.toString();
        StringBuilder A0S23 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S23, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S23, "message_type  IN ('2', '1', '25', '3', '28', '13', '29')", " AND ", "(origin IS NULL OR origin != 1)", " AND ");
        A0S23.append("chat_row_id = ?");
        String obj = A0S23.toString();
        A0b = obj;
        StringBuilder A0S24 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S24, str, " FROM ", "available_message_view", " WHERE ");
        A0S24.append("message_type IN ('2', '1', '25', '3', '28', '13', '29', '9', '26')");
        A0T = A0S24.toString();
        A0a = AnonymousClass008.A0O(new StringBuilder(), obj, " ORDER BY _id DESC");
        StringBuilder A0S25 = AnonymousClass008.A0S("SELECT ");
        A0S25.append(A00("message", str));
        A0S25.append(", ");
        A0S25.append("file_size");
        A0S25.append(" FROM ");
        A0S25.append("message_media AS message_media");
        AnonymousClass008.A1Y(A0S25, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " WHERE ");
        A0S25.append("message_type IN ('2', '1', '25', '3', '28', '13', '29', '9', '26')");
        A0S = A0S25.toString();
        StringBuilder A0S26 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S26, str, " , message_forwarded.forward_score", " FROM ", "available_message_view AS message");
        AnonymousClass008.A1Y(A0S26, " JOIN ", "message_forwarded AS message_forwarded", " ON message_forwarded.message_row_id = message._id", " WHERE ");
        String A0P2 = AnonymousClass008.A0P(A0S26, "message_forwarded.forward_score >= ?", " AND ", "message_type IN ('2', '1', '25', '3', '28', '13', '29', '9', '26')");
        A0G = A0P2;
        A0D = AnonymousClass008.A0O(new StringBuilder(), A0P2, " ORDER BY _id DESC");
        A0C = AnonymousClass008.A0O(new StringBuilder(), A0P2, " ORDER BY _id ASC");
        StringBuilder A0S27 = AnonymousClass008.A0S("SELECT ");
        A0S27.append(A00("message", str));
        A0S27.append(", ");
        A0S27.append("file_size");
        A0S27.append(" FROM ");
        A0S27.append("message_media AS message_media");
        AnonymousClass008.A1Y(A0S27, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " JOIN ");
        AnonymousClass008.A1Y(A0S27, "message_forwarded AS message_forwarded", " ON message_forwarded.message_row_id = message_media.message_row_id", " WHERE ", "message_forwarded.forward_score > ?");
        A0E = AnonymousClass008.A0P(A0S27, " AND ", "message_type IN ('2', '1', '25', '3', '28', '13', '29', '9', '26')", " ORDER BY file_size DESC");
        StringBuilder sb3 = new StringBuilder();
        String str3 = A0G;
        A0F = AnonymousClass008.A0O(sb3, str3, " ORDER BY media_size DESC");
        A0B = AnonymousClass008.A0O(new StringBuilder(), str3, " ORDER BY message_forwarded.forward_score DESC");
        StringBuilder A0S28 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S28, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S28, "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", "(origin IS NULL OR origin != 1)", " AND ");
        A0Y = AnonymousClass008.A0O(A0S28, "chat_row_id = ?", " ORDER BY _id DESC");
        StringBuilder A0S29 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S29, str, " FROM ", "available_message_view", " WHERE ");
        A0Z = AnonymousClass008.A0Q(A0S29, "((message_type = '2' AND origin != 1) OR message_type in ('1' , '25' , '3' , '28' , '13' , '29' , '23') )", " AND ", "chat_row_id = ?", " ORDER BY _id DESC");
        StringBuilder sb4 = new StringBuilder();
        sb4.append("SELECT ");
        AnonymousClass008.A1Y(sb4, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(sb4, "+message_type in (2 , 1 , 25 , 3 , 28 , 13 , 29 , 20 , 9 , 26 , 23 , 37 ) ", " AND ", "from_me = 0", " AND ");
        A0q = AnonymousClass008.A0O(sb4, "_id > ? ", " ORDER BY _id ASC");
        StringBuilder A0S30 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S30, str, " FROM ", "available_message_view", " WHERE ");
        A0S30.append(" ");
        A0S30.append("message_type");
        A0S30.append(" = '");
        A0S30.append(9);
        A0A = AnonymousClass008.A0P(A0S30, "' AND ", "chat_row_id", " = ? ");
        StringBuilder A0S31 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S31, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S31, "_id", " IN (", "SELECT docid FROM ", "messages_fts");
        AnonymousClass008.A1Y(A0S31, " AS messages_fts, ", "available_message_view", " AS message ", " WHERE content MATCH ? AND ");
        AnonymousClass008.A1Y(A0S31, "messages_fts.docid = ", "message.", "_id", " AND ");
        A0S31.append("message.");
        A0S31.append("message_type");
        A0S31.append(" IN ('");
        A0S31.append(9);
        A0S31.append("' , '");
        A0S31.append(26);
        A0S31.append("' ) AND ");
        A0S31.append("message.chat_row_id = ?) ");
        A09 = AnonymousClass008.A0P(A0S31, " ORDER BY ", "_id", " DESC");
        StringBuilder A0S32 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S32, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S32, "_id", " IN (", "SELECT docid FROM ", "message_ftsv2");
        AnonymousClass008.A1Y(A0S32, " AS ", "message_ftsv2", ", ", "available_message_view");
        AnonymousClass008.A1Y(A0S32, " AS message ", " WHERE ", "message_ftsv2", " MATCH ? AND ");
        A0R = AnonymousClass008.A0Q(A0S32, "message_ftsv2.docid = message._id) ", " ORDER BY ", "_id", " DESC");
        StringBuilder A0S33 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S33, str, " FROM ", "available_message_view", " WHERE ");
        A0S33.append("message_type");
        A0S33.append(" in ('");
        A0S33.append(9);
        A0S33.append("' , '");
        A0S33.append(26);
        A0S33.append("' ) AND ");
        A0S33.append("origin");
        A0S33.append(" != ");
        A0S33.append(7);
        A0S33.append(" AND ");
        A0S33.append("chat_row_id");
        A0S33.append(" = ? ");
        A08 = AnonymousClass008.A0P(A0S33, " ORDER BY ", "_id", " DESC");
        StringBuilder A0S34 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S34, str, ", link.link_index AS link_index", " FROM ", "(SELECT message_row_id, link_index FROM message_link)");
        AnonymousClass008.A1Y(A0S34, " AS link", " JOIN ", "available_message_view AS message", " ON message._id = link.message_row_id");
        A0M = AnonymousClass008.A0O(A0S34, " WHERE ", "chat_row_id = ?");
        StringBuilder A0S35 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S35, str, ", links.link_index AS link_index FROM ", " (SELECT message_row_id, link_index FROM ", "messages_links");
        AnonymousClass008.A1Y(A0S35, " AS links JOIN ", "jid", " AS jid ON jid.raw_string = links.key_remote_jid ", " JOIN ");
        AnonymousClass008.A1Y(A0S35, "chat", " AS chat ON jid._id = chat.jid_row_id ", " WHERE ", " chat._id = ?) links");
        AnonymousClass008.A1Y(A0S35, " JOIN ", "available_message_view", " AS message ON ", " message.");
        A0N = AnonymousClass008.A0O(A0S35, "_id", " = links.message_row_id ");
        StringBuilder A0S36 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S36, str, ", links.link_index AS link_index FROM ", "available_message_view AS message", ", ");
        AnonymousClass008.A1Y(A0S36, "(SELECT message_row_id, link_index FROM ", "messages_links AS links", " WHERE ", "links.key_remote_jid=?");
        AnonymousClass008.A1Y(A0S36, " AND ", "message_row_id IN ( ", "SELECT docid FROM ", "messages_fts");
        AnonymousClass008.A1Y(A0S36, ", ", "message_view", " AS message", " WHERE content MATCH ? AND ");
        AnonymousClass008.A1Y(A0S36, "messages_fts", ".docid = message.", "_id", ")");
        AnonymousClass008.A1Y(A0S36, ") links", " WHERE ", "message._id = links.message_row_id", " ORDER BY ");
        A0J = AnonymousClass008.A0O(A0S36, "_id", " DESC");
        StringBuilder A0S37 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S37, str, ", links.link_index AS link_index FROM ", "available_message_view", " AS message");
        AnonymousClass008.A1Y(A0S37, ", ", "(SELECT message_row_id, link_index FROM ", "messages_links", " WHERE message_row_id IN ( ");
        AnonymousClass008.A1Y(A0S37, "SELECT docid FROM ", "message_ftsv2", ", ", "message_view");
        AnonymousClass008.A1Y(A0S37, " AS message", " WHERE ", "message_ftsv2", " MATCH ? AND ");
        AnonymousClass008.A1Y(A0S37, "message_ftsv2", ".docid = message.", "_id", ")");
        AnonymousClass008.A1Y(A0S37, ") links", " WHERE ", "message.", "_id");
        A0K = AnonymousClass008.A0Q(A0S37, " = links.message_row_id", " ORDER BY ", "_id", " DESC");
        StringBuilder A0S38 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S38, str, ", links.link_index AS link_index FROM ", "available_message_view", " AS message, ");
        AnonymousClass008.A1Y(A0S38, "(SELECT message_row_id, link_index FROM ", "messages_links", " WHERE ", "messages_links");
        AnonymousClass008.A1Y(A0S38, ".key_remote_jid=?) links", " WHERE message.", "_id", " = links.message_row_id ");
        A0L = AnonymousClass008.A0P(A0S38, " ORDER BY ", "_id", " DESC");
        StringBuilder A0S39 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S39, str, ", links.link_index AS link_index FROM ", "message_view AS message", ", ");
        A0O = AnonymousClass008.A0Q(A0S39, "(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id=? AND message_row_id IN ( SELECT docid FROM messages_fts, message_view AS message WHERE content MATCH ? AND messages_fts.docid = message._id)) links", " WHERE ", "message._id = links.message_row_id ", " ORDER BY _id DESC");
        StringBuilder A0S40 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S40, str, ", links.link_index AS link_index FROM ", "message_view AS message", ", ");
        AnonymousClass008.A1Y(A0S40, "(SELECT message_row_id, link_index FROM message_link WHERE message_row_id IN ( SELECT docid FROM message_ftsv2, message_view AS message WHERE message_ftsv2 MATCH ? AND message_ftsv2.docid = message._id)) links", " WHERE ", "message.", "_id");
        A0P = AnonymousClass008.A0O(A0S40, " = links.message_row_id ", " ORDER BY _id DESC");
        StringBuilder A0S41 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S41, str, ", links.link_index AS link_index FROM ", "message_view AS message", ", ");
        A0Q = AnonymousClass008.A0Q(A0S41, "(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id = ?) links", " WHERE ", "message._id = links.message_row_id", " ORDER BY _id DESC");
        A0s = AnonymousClass008.A0P(AnonymousClass008.A0S("SELECT "), str, " FROM available_message_view as message WHERE (_id IN (SELECT message_row_id FROM message_quoted WHERE message_row_id=message._id AND key_id = 'product_inquiry') OR message_type = '23' ) AND chat_row_id = ?", " ORDER BY _id DESC");
        StringBuilder A0S42 = AnonymousClass008.A0S("SELECT ");
        A0S42.append(A00("message", str));
        A0S42.append(", transaction_id");
        A0S42.append(" FROM ");
        A0S42.append("call_logs");
        A0S42.append(" call_logs");
        AnonymousClass008.A1Y(A0S42, " INNER JOIN ", "message_view", " message", " ON call_logs.message_row_id=message._id");
        A04 = AnonymousClass008.A0Q(A0S42, " WHERE ", "message_type = '8'", " ORDER BY call_logs._id DESC", " LIMIT ?,?");
        StringBuilder A0S43 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S43, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S43, "message_type = '8'", " AND ", "media_caption IS NOT NULL", " ORDER BY ");
        A03 = AnonymousClass008.A0O(A0S43, "_id", " DESC LIMIT ?,?");
        StringBuilder A0S44 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S44, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S44, "from_me = 0", " AND ", "message_type = '8'", " AND ");
        AnonymousClass008.A1Y(A0S44, "media_caption IS NOT NULL", " AND ", "media_duration = 0", " AND ");
        AnonymousClass008.A1Y(A0S44, "media_size = 0", " AND ", "timestamp > ?", " ORDER BY _id DESC ");
        A0S44.append("LIMIT 100");
        A0l = A0S44.toString();
        StringBuilder A0S45 = AnonymousClass008.A0S("SELECT ");
        A0S45.append(A00("message", str));
        A0S45.append(", transaction_id");
        A0S45.append(" FROM ");
        A0S45.append("call_logs AS call_logs");
        A0S45.append(" INNER JOIN ");
        AnonymousClass008.A1Y(A0S45, "message_view AS message", " ON call_logs.message_row_id = message._id", " WHERE ", "message.from_me = 0");
        AnonymousClass008.A1Y(A0S45, " AND ", "message.message_type = 8", " AND ", "call_logs.call_result = 2");
        A0m = AnonymousClass008.A0Q(A0S45, " AND ", "call_logs.timestamp >= ?", " ORDER BY call_logs._id DESC", " LIMIT 100");
        StringBuilder A0S46 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S46, A00, ", ", "key_remote_jid", " FROM ");
        A0S46.append("legacy_available_messages_view");
        A0S46.append(" WHERE key_from_me=0 AND media_wa_type=");
        A0S46.append(12);
        A0S46.append(" ORDER BY ");
        A0S46.append("_id");
        A0z = A0S46.toString();
        StringBuilder A0S47 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S47, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S47, "from_me = 0", " AND ", "message_type = 12", " ORDER BY ");
        A0S47.append("_id");
        A0y = A0S47.toString();
        StringBuilder A0S48 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S48, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S48, "from_me = 1", " AND ", "status < 4", " AND ");
        A1H = AnonymousClass008.A0O(A0S48, "_id > ?", " ORDER BY _id ASC");
        StringBuilder A0S49 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S49, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S49, "from_me = 1 ", " AND ", "chat_row_id = ? ", " AND ");
        AnonymousClass008.A1Y(A0S49, "status < 4", " AND ", "timestamp > ? ", " AND ");
        A1G = AnonymousClass008.A0O(A0S49, "timestamp < ? ", " ORDER BY timestamp ASC");
        StringBuilder A0S50 = AnonymousClass008.A0S("SELECT ");
        A0S50.append(A00("message", str));
        A0S50.append(" FROM ");
        A0S50.append("available_message_view AS message");
        A0S50.append(" JOIN ");
        A0S50.append("chat AS chat");
        AnonymousClass008.A1Y(A0S50, " ON message.chat_row_id = chat._id", " WHERE ", "message.from_me = 0", " AND ");
        AnonymousClass008.A1Y(A0S50, "status != 16", " AND ", "status != 10", " AND ");
        AnonymousClass008.A1Y(A0S50, "(chat.last_read_message_row_id >= message._id OR status = 17)", " AND ", "chat.last_read_receipt_sent_message_row_id < message._id", " AND ");
        AnonymousClass008.A1Y(A0S50, "chat.last_read_receipt_sent_message_row_id > 0", " AND ", "message.message_type NOT IN ('8', '10', '15')", " AND ");
        A1I = AnonymousClass008.A0Q(A0S50, "(chat.hidden IS NULL OR chat.hidden = 0)", " ORDER BY message.", "_id", " DESC LIMIT 4096");
        StringBuilder A0S51 = AnonymousClass008.A0S("SELECT ");
        A0S51.append(A00("message", str));
        A0S51.append(" FROM ");
        A0S51.append("available_message_view AS message");
        A0S51.append(" JOIN ");
        A0S51.append("chat AS chat_chat ON message.chat_row_id = chat_chat._id");
        AnonymousClass008.A1Y(A0S51, " JOIN ", "jid AS chat_jid ON chat_chat.jid_row_id = chat_jid._id", " JOIN ", "chat_view AS chat ON chat.raw_string_jid = chat_jid.raw_string");
        AnonymousClass008.A1Y(A0S51, " WHERE ", "message.from_me = 0", " AND ", "status != 16");
        AnonymousClass008.A1Y(A0S51, " AND ", "status != 10", " AND ", "(chat.last_read_message_row_id >= message._id OR status = 17)");
        AnonymousClass008.A1Y(A0S51, " AND ", "chat.last_read_receipt_sent_message_row_id < message._id", " AND ", "chat.last_read_receipt_sent_message_row_id > 0");
        AnonymousClass008.A1Y(A0S51, " AND ", "message.message_type NOT IN ('8', '10', '15')", " AND ", "(chat.hidden IS NULL OR chat.hidden = 0)");
        A1J = AnonymousClass008.A0P(A0S51, " ORDER BY message.", "_id", " DESC LIMIT 4096");
        StringBuilder A0S52 = AnonymousClass008.A0S("SELECT ");
        A0S52.append(A00("message", str));
        A0S52.append(" FROM ");
        A0S52.append("message_view AS message");
        A0S52.append(" JOIN ");
        A0S52.append("status_list AS chat_list");
        AnonymousClass008.A1Y(A0S52, " ON ", "chat_list.key_remote_jid = message.", "sender_jid_raw_string", " WHERE ");
        AnonymousClass008.A1Y(A0S52, "message.chat_row_id = ?", " AND ", "message.from_me = 0", " AND ");
        AnonymousClass008.A1Y(A0S52, "chat_list.last_read_message_table_id >= message._id", " AND ", "chat_list.last_read_receipt_sent_message_table_id < message._id", " AND ");
        AnonymousClass008.A1Y(A0S52, "chat_list.last_read_receipt_sent_message_table_id > 0", " AND ", "message.message_type != '15'", " ORDER BY message.");
        A1M = AnonymousClass008.A0O(A0S52, "_id", " DESC LIMIT 4096");
        StringBuilder A0S53 = AnonymousClass008.A0S("SELECT ");
        A0S53.append(A00("message", str));
        A0S53.append(" FROM ");
        A0S53.append("message_view AS message");
        A0S53.append(" JOIN ");
        A0S53.append("jid AS jid");
        AnonymousClass008.A1Y(A0S53, " ON jid.raw_string=message.sender_jid_raw_string", " JOIN ", "status AS status_list", " ON ");
        AnonymousClass008.A1Y(A0S53, "status_list.jid_row_id = jid._id", " WHERE ", "message.chat_row_id = ?", " AND ");
        AnonymousClass008.A1Y(A0S53, "message.from_me = 0", " AND ", "status_list.last_read_message_table_id >= message._id", " AND ");
        AnonymousClass008.A1Y(A0S53, "status_list.last_read_receipt_sent_message_table_id < message._id", " AND ", "status_list.last_read_receipt_sent_message_table_id > 0", " AND ");
        A1N = AnonymousClass008.A0Q(A0S53, "message.message_type != '15'", " ORDER BY message.", "_id", " DESC LIMIT 4096");
        StringBuilder A0S54 = AnonymousClass008.A0S("SELECT ");
        A0S54.append(A00("message", str));
        A0S54.append(" FROM ");
        A0S54.append("message_view AS message");
        A0S54.append(" JOIN ");
        A0S54.append("status AS status_list");
        AnonymousClass008.A1Y(A0S54, " ON ", "status_list.jid_row_id = message.sender_jid_row_id", " WHERE ", "message.chat_row_id = ?");
        AnonymousClass008.A1Y(A0S54, " AND ", "message.from_me = 0", " AND ", "status_list.last_read_message_table_id >= message._id");
        AnonymousClass008.A1Y(A0S54, " AND ", "status_list.last_read_receipt_sent_message_table_id < message._id", " AND ", "status_list.last_read_receipt_sent_message_table_id > 0");
        AnonymousClass008.A1Y(A0S54, " AND ", "message.message_type != '15'", " ORDER BY message.", "_id");
        A0S54.append(" DESC LIMIT 4096");
        A1L = A0S54.toString();
        StringBuilder A0S55 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S55, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S55, "chat_row_id = ?", " AND ", "from_me = 0", " AND ");
        AnonymousClass008.A1Y(A0S55, "_id <= ?", " AND ", "_id > ?", " AND ");
        AnonymousClass008.A1Y(A0S55, "status NOT IN (16, 10)", " AND ", "message_type NOT IN ('8', '10', '15')", " ORDER BY ");
        A1K = AnonymousClass008.A0O(A0S55, "_id", " DESC LIMIT 4096");
        StringBuilder sb5 = new StringBuilder();
        AnonymousClass008.A1Y(sb5, str, ", ", "messages_fts.docid AS docid", ", ");
        sb5.append("messages_fts.content AS content");
        String obj2 = sb5.toString();
        A13 = obj2;
        A15 = AnonymousClass008.A0Q(AnonymousClass008.A0S("SELECT "), obj2, " FROM ", "message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message._id", " WHERE content MATCH ?");
        StringBuilder A0S56 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S56, obj2, " FROM ", "available_message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message._id", " WHERE ");
        A14 = AnonymousClass008.A0P(A0S56, "content MATCH ?", " AND ", "chat_row_id = ?");
        StringBuilder A0S57 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S57, str, ", ", "docid", ", ");
        AnonymousClass008.A1Y(A0S57, "content", ", ", "fts_jid", " FROM ");
        AnonymousClass008.A1Y(A0S57, "message_ftsv2 AS fts", " JOIN ", "available_message_view AS message", " ON ");
        A16 = AnonymousClass008.A0Q(A0S57, "fts.docid = message._id", " WHERE ", "message_ftsv2", " MATCH ? ");
        StringBuilder A0S58 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S58, str, " FROM ", "available_message_view", " WHERE ");
        A02 = AnonymousClass008.A0P(A0S58, "starred = 1", " AND ", "(message_type != '7')");
        StringBuilder A0S59 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S59, str, " FROM ", "message_view", " WHERE ");
        A19 = AnonymousClass008.A0Q(A0S59, "_id", " IN ", "( \n   SELECT docid \n   FROM messages_fts AS messages_fts, available_message_view AS message \n   WHERE content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1 AND (message_type != '7'))\n", " ORDER BY _id DESC");
        StringBuilder A0S60 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S60, str, " FROM ", "message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S60, "_id", " IN ", "( \n   SELECT docid \n   FROM message_ftsv2 AS messages_fts, available_message_view AS message \n   WHERE messages_fts.content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1   AND (message_type != '7'))\n", " ORDER BY ");
        A1A = AnonymousClass008.A0O(A0S60, "_id", " DESC");
        StringBuilder A0S61 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S61, str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass008.A1Y(A0S61, "chat_row_id = ?", " AND ", "starred = 1", " AND ");
        A0S61.append("(message_type != '7')");
        A01 = A0S61.toString();
        StringBuilder A0S62 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S62, str, " FROM ", "available_message_view", " WHERE ");
        A17 = AnonymousClass008.A0Q(A0S62, "_id", " IN ", "(SELECT docid FROM messages_fts AS messages_fts, message_view AS message WHERE chat_row_id = ? AND messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY _id DESC");
        StringBuilder A0S63 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S63, str, " FROM ", "available_message_view", " WHERE ");
        A18 = AnonymousClass008.A0Q(A0S63, "_id", " IN ", "(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY _id DESC");
        StringBuilder sb6 = new StringBuilder();
        String str4 = A05;
        A0f = AnonymousClass008.A0Q(sb6, str4, " ORDER BY ", "_id", " DESC LIMIT ?");
        StringBuilder sb7 = new StringBuilder();
        AnonymousClass008.A1Y(sb7, str4, " AND ", "_id", ">=? ORDER BY ");
        A0g = AnonymousClass008.A0O(sb7, "_id", " ASC");
        StringBuilder A0S64 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S64, str, ", remove_files ", " FROM ", "deleted_messages_view");
        AnonymousClass008.A1Y(A0S64, " WHERE ", "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", "chat_row_id");
        A0S64.append(" = ?");
        A0U = A0S64.toString();
        StringBuilder A0S65 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S65, str, ", deleted_msg.remove_files AS remove_files", " FROM ", "deleted_messages_view");
        AnonymousClass008.A1Y(A0S65, " AS deleted_msg ", " WHERE ", "chat_row_id", " = ? AND ");
        A0S65.append("message_type");
        A0S65.append(" != ");
        A0S65.append(8);
        A0S65.append(" ORDER BY _id ASC");
        A0S65.append(" LIMIT ?");
        A07 = A0S65.toString();
        StringBuilder A0Y2 = AnonymousClass008.A0Y("SELECT key_remote_jid, sum(media_size) as media_sum FROM messages WHERE media_wa_type IN ('0','1','2','3','4','5','9','13','14') AND ", "key_remote_jid != '");
        A0Y2.append(C12060hU.A00.getRawString());
        A0Y2.append("' GROUP BY ");
        A0Y2.append("key_remote_jid");
        A0Y2.append(" ORDER BY media_sum DESC");
        A06 = A0Y2.toString();
        StringBuilder A0S66 = AnonymousClass008.A0S("SELECT ");
        AnonymousClass008.A1Y(A0S66, str, " FROM ", "message_ephemeral", " me JOIN ");
        AnonymousClass008.A1Y(A0S66, "available_message_view", " vam ON me.message_row_id=vam._id", " WHERE me.", "expire_timestamp");
        A0S66.append("<?");
        A1C = A0S66.toString();
    }

    public static String A00(String str, String str2) {
        String[] split = str2.replaceAll(" ", "").split(",");
        for (int i = 0; i < split.length; i++) {
            StringBuilder A0Y2 = AnonymousClass008.A0Y(str, ".");
            String str3 = split[i];
            A0Y2.append(str3);
            A0Y2.append(" AS ");
            A0Y2.append(str3);
            split[i] = A0Y2.toString();
        }
        return TextUtils.join(", ", split);
    }
}
