package X;

import java.util.List;

/* renamed from: X.0zi  reason: invalid class name and case insensitive filesystem */
public class C22020zi {
    public final double A00;
    public final double A01;
    public final double A02;
    public final float A03;
    public final int A04;
    public final int A05;
    public final int A06;
    public final int A07;
    public final int A08;
    public final int A09;
    public final int A0A;
    public final int A0B;
    public final int A0C;
    public final int A0D;
    public final int A0E;
    public final int A0F;
    public final int A0G;
    public final int A0H;
    public final int A0I;
    public final int A0J;
    public final int A0K;
    public final long A0L;
    public final long A0M;
    public final C07070Vu A0N;
    public final C07070Vu A0O;
    public final C07070Vu A0P;
    public final C07070Vu A0Q;
    public final String A0R;
    public final List A0S;
    public final List A0T;
    public final boolean A0U;
    public final boolean A0V;
    public final boolean A0W;
    public final boolean A0X;
    public final boolean A0Y;
    public final boolean A0Z;
    public final boolean A0a;
    public final boolean A0b;
    public final boolean A0c;
    public final boolean A0d;
    public final boolean A0e;
    public final boolean A0f;
    public final boolean A0g;
    public final boolean A0h;
    public final boolean A0i;
    public final boolean A0j;
    public final boolean A0k;
    public final boolean A0l;
    public final boolean A0m;
    public final boolean A0n;
    public final boolean A0o;
    public final boolean A0p;
    public final boolean A0q;
    public final boolean A0r;
    public final boolean A0s;
    public final boolean A0t;
    public final boolean A0u;
    public final boolean A0v;
    public final boolean A0w;
    public final boolean A0x;
    public final boolean A0y;
    public final boolean A0z;
    public final boolean A10;
    public final boolean A11;
    public final boolean A12;
    public final boolean A13;
    public final boolean A14;
    public final boolean A15;
    public final boolean A16;
    public final boolean A17;
    public final boolean A18;
    public final boolean A19;
    public final boolean A1A;
    public final boolean A1B;
    public final boolean A1C;
    public final boolean A1D;
    public final boolean A1E;
    public final boolean A1F;
    public final boolean A1G;
    public final boolean A1H;
    public final boolean A1I;
    public final boolean A1J;
    public final boolean A1K;
    public final float[] A1L;
    public final int[] A1M;
    public final int[] A1N;

    public C22020zi(C22010zh r3) {
        this.A0p = r3.A0p;
        this.A0U = r3.A0U;
        this.A0h = r3.A0h;
        this.A0b = r3.A0b;
        this.A0d = r3.A0d;
        this.A0n = r3.A0n;
        this.A0j = r3.A0j;
        this.A0o = r3.A0o;
        this.A10 = r3.A10;
        this.A11 = r3.A11;
        this.A12 = r3.A12;
        this.A13 = r3.A13;
        this.A17 = r3.A17;
        this.A18 = r3.A18;
        this.A19 = r3.A19;
        this.A1B = r3.A1B;
        this.A1A = r3.A1A;
        this.A1C = r3.A1C;
        this.A1F = r3.A1F;
        this.A1I = r3.A1I;
        this.A15 = r3.A15;
        this.A1G = r3.A1G;
        this.A1J = r3.A1J;
        this.A1K = r3.A1K;
        this.A0y = r3.A0y;
        this.A1E = r3.A1E;
        this.A0s = r3.A0s;
        this.A0u = r3.A0u;
        this.A0t = r3.A0t;
        this.A0v = r3.A0v;
        this.A0w = r3.A0w;
        this.A16 = r3.A16;
        this.A0z = r3.A0z;
        this.A0m = r3.A0m;
        this.A0r = r3.A0r;
        this.A0X = r3.A0X;
        this.A0l = r3.A0l;
        this.A0Z = r3.A0Z;
        this.A0i = r3.A0i;
        this.A0V = r3.A0V;
        this.A0e = r3.A0e;
        this.A0f = r3.A0f;
        this.A0g = r3.A0g;
        this.A0A = r3.A0A;
        this.A04 = r3.A04;
        this.A06 = r3.A06;
        this.A0a = r3.A0a;
        this.A0c = r3.A0c;
        this.A09 = r3.A09;
        this.A08 = r3.A08;
        this.A0S = r3.A0S;
        this.A0C = r3.A0C;
        this.A0D = r3.A0D;
        this.A0N = r3.A0N;
        this.A0T = r3.A0T;
        this.A0F = r3.A0F;
        this.A0O = r3.A0O;
        this.A0G = r3.A0G;
        this.A0H = r3.A0H;
        this.A1N = r3.A1N;
        this.A0P = r3.A0P;
        this.A0I = r3.A0I;
        this.A1H = r3.A1H;
        this.A14 = r3.A14;
        this.A0Q = r3.A0Q;
        this.A0J = r3.A0J;
        this.A0K = r3.A0K;
        this.A0x = r3.A0x;
        this.A1D = r3.A1D;
        this.A00 = r3.A00;
        this.A02 = r3.A02;
        this.A01 = r3.A01;
        this.A0R = r3.A0R;
        this.A0M = r3.A0M;
        this.A0E = r3.A0E;
        this.A0B = r3.A0B;
        this.A0L = r3.A0L;
        this.A07 = r3.A07;
        this.A0q = r3.A0q;
        this.A0W = r3.A0W;
        this.A0k = r3.A0k;
        this.A0Y = r3.A0Y;
        this.A03 = r3.A03;
        this.A1L = r3.A1L;
        this.A05 = r3.A05;
        this.A1M = r3.A1M;
    }
}
