package X;

import android.util.SparseArray;
import java.util.Arrays;
import java.util.HashSet;
import java.util.regex.Pattern;

/* renamed from: X.2Ju  reason: invalid class name and case insensitive filesystem */
public class C47852Ju {
    public static Pattern A00 = Pattern.compile("^[a-z0-9\\-]+$");
    public static final SparseArray A01;
    public static final C47832Js A02;
    public static final HashSet A03 = new HashSet(Arrays.asList(1072, 1074, 1075, 1077, 1082, 1084, 1085, 1086, 1088, 1089, 1090, 1091, 1093, 1096, 1097, 1100, 1109, 1110, 1112, 1121, 1141, 1199, 1211, 1231, 1281, 1307, 1309, 1319, 42649));
    public static final HashSet A04 = new HashSet(Arrays.asList("AM", "AZ", "BY", "BA", "BG", "GE", "KZ", "XK", "KG", "MK", "MD", "MN", "ME", "RU", "RS", "TJ", "TM", "UA", "UZ"));
    public static final HashSet A05 = new HashSet(Arrays.asList("abq", "ab", "ady", "av", "az", "ba", "be", "bs", "bg", "bua", "ce", "ckt", "cu", "cv", "crh", "dar", "dng", "myv", "evn", "gag", "inh", "kbd", "xal", "krc", "kaa", "kk", "kjh", "kca", "ky", "kv", "koi", "kpy", "kum", "lbe", "lez", "mk", "mns", "chm", "mdf", "mn", "ttt", "gld", "yrk", "nog", "os", "ru", "rue", "sr", "sh", "cjs", "alt", "tab", "tg", "tt", "tkr", "tk", "tyv", "ude", "udm", "uk", "uz", "mrj", "sah"));

    static {
        C47832Js r2 = new C47832Js();
        A02 = r2;
        r2.A00("fub", "CM", "TD", "NG");
        C47832Js r7 = A02;
        r7.A00("af", "NA", "ZA");
        r7.A00("agq", "CM");
        r7.A00("yay", "NG");
        r7.A00("bss", "CM");
        r7.A00("agg", "PG");
        r7.A00("ast", "ES");
        r7.A00("avu", "CD", "SS");
        r7.A00("az", "AZ");
        r7.A00("bkc", "CM", "GA");
        r7.A00("ksf", "CM");
        r7.A00("bfd", "CM");
        r7.A00("bjt", "SN");
        r7.A00("bcn", "NG");
        r7.A00("bas", "CM");
        r7.A00("bsq", "LR");
        r7.A00("bkv", "NG");
        r7.A00("bom", "NG");
        r7.A00("btt", "NG");
        r7.A00("bin", "NG");
        r7.A00("bmq", "BF", "ML");
        r7.A00("bs", "BA", "HR", "XK", "ME", "RS");
        r7.A00("fue", "BJ", "TG");
        r7.A00("br", "FR");
        r7.A00("bys", "NG");
        r7.A00("bwr", "NG");
        r7.A00("cky", "NG");
        r7.A00("ca", "AD", "FR", "IT", "ES");
        r7.A00("tzm", "MA");
        r7.A00("fuq", "NG");
        r7.A00("ckl", "NG");
        r7.A00("asg", "NG");
        r7.A00("co", "FR", "IT");
        r7.A00("crh", "RU");
        r7.A00("hr", "BA", "HR", "XK", "ME", "RS");
        r7.A00("mfn", "NG");
        r7.A00("cs", "CZ", "SK");
        r7.A00("dbq", "CM", "NG");
        r7.A00("dnj", "CI", "LR");
        r7.A00("dzg", "TD", "NE");
        r7.A00("ddn", "BJ");
        r7.A00("dgh", "NG");
        r7.A00("dow", "CM");
        r7.A00("dua", "CM");
        r7.A00("nl", "AW", "BE", "CW", "NL", "SX", "SR");
        r7.A00("igb", "NG");
        r7.A00("etr", "PG");
        r7.A00("enn", "NG");
        r7.A00("kjy", "PG");
        r7.A00("et", "EE");
        r7.A00("ich", "NG");
        r7.A00("ee", "BJ", "GH", "TG");
        r7.A00("ewo", "CM");
        r7.A00("fo", "FO");
        r7.A00("fmp", "CM");
        r7.A00("fi", "FI", "SE");
        r7.A00("fr", "BE", "BJ", "BF", "BI", "CM", "CA", "CF", "CG", "CD", "TD", "KM", "DJ", "GQ", "FR", "GA", "HT", "CI", "LU", "MG", "ML", "MC", "NE", "RW", "SN", "SC", "CH", "TG", "VU");
        r7.A00("fur", "IT");
        r7.A00("ff", "CM", "GN", "MR", "SN");
        r7.A00("gaj", "PG");
        r7.A00("gl", "ES");
        r7.A00("gby", "NG");
        r7.A00("gba", "CF");
        r7.A00("gmm", "CM");
        r7.A00("de", "AT", "BE", "DE", "LI", "LU", "CH");
        r7.A00("tof", "PG");
        r7.A00("god", "CI");
        r7.A00("ank", "NG");
        r7.A00("gkn", "NG");
        r7.A00("gux", "BJ", "BF", "NE", "TG");
        r7.A00("gde", "CM", "NG");
        r7.A00("gkp", "GN");
        r7.A00("kl", "GL");
        r7.A00("jgk", "NG");
        r7.A00("ha", "BJ", "CM", "TD", "GH", "CI", "NE", "NG", "SD", "TG");
        r7.A00("haw", "US");
        r7.A00("hbb", "NG");
        r7.A00("hu", "HU");
        r7.A00("dud", "NG");
        r7.A00("jab", "NG");
        r7.A00("iby", "NG");
        r7.A00("is", "IS");
        r7.A00("idu", "NG");
        r7.A00("ig", "GQ");
        r7.A00("ige", "NG");
        r7.A00("ikx", "UG");
        r7.A00("ikk", "NG");
        r7.A00("ikw", "NG");
        r7.A00("smn", "FI");
        r7.A00("ga", "IE", "GB");
        r7.A00("atg", "NG");
        r7.A00("izi", "NG");
        r7.A00("dyo", "GM", "SN");
        r7.A00("jbu", "CM", "NG");
        r7.A00("kab", "DZ");
        r7.A00("kea", "CV");
        r7.A00("tbd", "PG");
        r7.A00("hig", "NG");
        r7.A00("kai", "NG");
        r7.A00("kkj", "CM", "CF", "CG");
        r7.A00("kzr", "CM", "TD");
        r7.A00("naq", "NA");
        r7.A00("geb", "PG");
        r7.A00("okr", "NG");
        r7.A00("ksh", "DE");
        r7.A00("ses", "ML");
        r7.A00("khq", "ML");
        r7.A00("kun", "ER", "ET");
        r7.A00("kup", "PG");
        r7.A00("kub", "CM", "NG");
        r7.A00("kpe", "GN", "LR");
        r7.A00("nmg", "CM", "GQ");
        r7.A00("ku", "SY", "TR");
        r7.A00("lkt", "US");
        r7.A00("hia", "NG");
        r7.A00("lag", "TZ");
        r7.A00("lv", "LV");
        r7.A00("lmp", "CM");
        r7.A00("ln", "CG", "CD");
        r7.A00("liv", new String[0]);
        r7.A00("lt", "LT");
        r7.A00("yaz", "NG");
        r7.A00("nds", "BR", "DE", "NL");
        r7.A00("dsb", "DE");
        r7.A00("lu", "CD");
        r7.A00("lb", "BE", "FR", "DE", "LU");
        r7.A00("mda", "NG");
        r7.A00("mg", "MG");
        r7.A00("mt", "MT");
        r7.A00("mi", "NZ");
        r7.A00("arn", "CL");
        r7.A00("mas", "KE", "TZ");
        r7.A00("bin", "ML");
        r7.A00("mql", "BJ", "TG");
        r7.A00("mbo", "CM");
        r7.A00("mbu", "NG");
        r7.A00("mif", "CM");
        r7.A00("mzm", "NG");
        r7.A00("mua", "CM", "TD");
        r7.A00("sur", "NG");
        r7.A00("nv", "US");
        r7.A00("anc", "NG");
        r7.A00("nnh", "CM");
        r7.A00("jgo", "CM");
        r7.A00("fuv", "CM", "NG");
        r7.A00("nin", "NG");
        r7.A00("dgi", "BF");
        r7.A00("se", "FI", "SE", "NO");
        r7.A00("nso", "ZA");
        r7.A00("ann", "NG");
        r7.A00("oc", "FR", "IT", "MC", "ES");
        r7.A00("pbi", "CM");
        r7.A00("pip", "NG");
        r7.A00("pl", "PL");
        r7.A00("pt", "AO", "BR", "CV", "GQ", "GW", "MO", "MZ", "PT", "ST", "TL");
        r7.A00("prg", new String[0]);
        r7.A00("fuf", "GN", "ML", "SN", "SL");
        r7.A00("qu", "AR", "BO", "CO", "EC", "PE");
        r7.A00("ro", "MD", "RO");
        r7.A00("cla", "NG");
        r7.A00("sav", "SN");
        r7.A00("sg", "CF", "TD", "CD");
        r7.A00("gd", "GB");
        r7.A00("seh", "MZ");
        r7.A00("sr", "BA", "HR", "XK", "ME", "RS");
        r7.A00("sh", "BA", "HR", "XK", "ME", "RS");
        r7.A00("srr", "GM", "SN");
        r7.A00("scn", "IT");
        r7.A00("sld", "BF");
        r7.A00("sms", "FI");
        r7.A00("sk", "CZ", "SK");
        r7.A00("sl", "SI");
        r7.A00("sok", "TD");
        r7.A00("es", "AR", "BZ", "BO", "IC", "EA", "CL", "CO", "CR", "CU", "DO", "EC", "SV", "GQ", "GT", "HN", "MX", "NI", "PA", "PY", "PE", "PR", "ES", "US", "UY", "VE");
        r7.A00("srn", "SR");
        r7.A00("gsw", "AT", "FR", "DE", "LI", "CH");
        r7.A00("shi", "MA");
        r7.A00("tal", "NG");
        r7.A00("tmh", "ML");
        r7.A00("taq", "BF", "ML");
        r7.A00("tan", "NG");
        r7.A00("twq", "NE");
        r7.A00("blt", "LA", "VN");
        r7.A00("yer", "NG");
        r7.A00("tuq", "TD", "LY", "NE", "NG");
        r7.A00("ttr", "NG");
        r7.A00("tik", "CM");
        r7.A00("to", "TO");
        r7.A00("dts", "ML");
        r7.A00("kdl", "NG");
        r7.A00("tsw", "NG");
        r7.A00("tr", "TR");
        r7.A00("tk", "TM");
        r7.A00("hsb", "DE");
        r7.A00("vai", "LR", "SL");
        r7.A00("vi", "KH", "VN");
        r7.A00("vo", new String[0]);
        r7.A00("vut", "CM", "NG");
        r7.A00("wja", "NG");
        r7.A00("wa", "BE");
        r7.A00("wae", "AT", "IT", "LI", "CH");
        r7.A00("wji", "NG");
        r7.A00("cy", "GB");
        r7.A00("fy", "NL");
        r7.A00("fuh", "BJ", "BF", "NE");
        r7.A00("yba", "NG");
        r7.A00("yav", "CM");
        r7.A00("yle", "PG");
        r7.A00("yll", "PG");
        r7.A00("yo", "BJ", "NG");
        r7.A00("dje", "NE");
        r7.A00("gnd", "CM");
        SparseArray sparseArray = new SparseArray();
        A01 = sparseArray;
        sparseArray.append(237, new C47842Jt("ast", "ksf", "bas", "ca", "cs", "dua", "nl", "ee", "ewo", "fo", "fr", "gl", "kl", "hu", "is", "ga", "dyo", "kea", "kkj", "nmg", "lkt", "lag", "ln", "lu", "mas", "nnh", "jgo", "pt", "qu", "seh", "sk", "es", "to", "vai", "vi", "wae", "cy", "fy", "yav", "yo"));
        SparseArray sparseArray2 = A01;
        sparseArray2.append(238, new C47842Jt("af", "agq", "bss", "bfd", "bas", "bkv", "btt", "nl", "igb", "ewo", "fr", "fur", "gaj", "gby", "kl", "jab", "atg", "jbu", "kkj", "naq", "ksh", "ku", "nmg", "lmp", "ln", "mda", "mg", "mas", "mzm", "jgo", "nin", "ann", "ro", "sg", "scn", "srn", "yer", "tr", "wa", "cy", "yav", "yle"));
        sparseArray2.append(252, new C47842Jt("agg", "ast", "az", "br", "ca", "co", "cs", "nl", "etr", "et", "fr", "gl", "de", "tof", "god", "hu", "tbd", "geb", "ksh", "kup", "nds", "lb", "arn", "oc", "sg", "sk", "es", "gsw", "dts", "tr", "tk", "vo", "wa", "wae", "fy", "yll"));
        sparseArray2.append(267, new C47842Jt("mt"));
        sparseArray2.append(299, new C47842Jt("agq", "bss", "bfd", "bas", "bkv", "btt", "ddn", "igb", "kjy", "ich", "gux", "haw", "jab", "iby", "idu", "jbu", "kub", "nmg", "lv", "mda", "mi", "mas", "mql", "nin", "prg", "gd", "to", "yba", "yav"));
        sparseArray2.append(305, new C47842Jt("az", "crh", "tr"));
        sparseArray2.append(316, new C47842Jt("lv"));
        sparseArray2.append(322, new C47842Jt("dsb", "nv", "pl", "hsb"));
        sparseArray2.append(353, new C47842Jt("bs", "hr", "cs", "dzg", "et", "fi", "smn", "geb", "khq", "ses", "kun", "lkt", "lv", "lt", "dsb", "se", "nso", "prg", "sr", "sh", "sms", "sk", "sl", "taq", "twq", "tuq", "hsb", "wae", "dje"));
        sparseArray2.append(409, new C47842Jt("ckl", "ank", "ha", "ikx", "kai", "hia", "mbu", "anc", "nin", "pip", "tal", "tan", "wja", "wji"));
        sparseArray2.append(448, new C47842Jt("naq"));
        sparseArray2.append(449, new C47842Jt("naq"));
        sparseArray2.append(559, new C47842Jt("liv"));
        sparseArray2.append(593, new C47842Jt("fmp", "dud", "tmh"));
        sparseArray2.append(595, new C47842Jt("fub", "yay", "bkc", "bjt", "bcn", "bas", "bsq", "bmq", "fue", "bys", "bwr", "cky", "fuq", "ckl", "asg", "dbq", "dnj", "dgh", "dow", "dua", "enn", "ff", "gby", "gba", "gmm", "ank", "gde", "gkp", "jgk", "ha", "hbb", "ikx", "kkj", "hig", "kzr", "kai", "kpe", "nmg", "hia", "bin", "mbo", "mbu", "mif", "mzm", "mua", "sur", "anc", "fuv", "nin", "dgi", "pbi", "pip", "fuf", "cla", "sav", "srr", "sld", "sok", "tal", "tan", "yer", "ttr", "tik", "kdl", "tsw", "vai", "vut", "wja", "wji", "fuh", "gnd"));
        sparseArray2.append(7693, new C47842Jt("tzm", "kab", "okr", "shi", "tmh", "taq"));
        sparseArray2.append(7771, new C47842Jt("tzm", "kab", "shi"));
        sparseArray2.append(7789, new C47842Jt("tzm", "kab", "shi", "tmh", "taq"));
        sparseArray2.append(7817, new C47842Jt(new String[0]));
        sparseArray2.append(7841, new C47842Jt("izi", "yaz", "blt", "vi"));
        sparseArray2.append(7865, new C47842Jt("yay", "bom", "bin", "mfn", "dzg", "igb", "enn", "gkn", "iby", "ikk", "ikw", "izi", "okr", "yaz", "blt", "tan", "tuq", "vi", "yo"));
        sparseArray2.append(7883, new C47842Jt("avu", "mfn", "igb", "enn", "iby", "ig", "ige", "ikk", "ikw", "izi", "okr", "blt", "tan", "vi"));
    }
}
